#!/bin/bash
if [ -z "$1" ]; then
  echo "No theme name provided. Usage: omp-usetm [theme_name]"
  exit 1
fi
uhost="$(whoami)@$(hostname)"
omp_path="$(brew --prefix oh-my-posh)"
theme_path="$omp_path/themes"

# Copy theme to $HOME directory
echo -e "\e[0;33mCopying \e[0m'\e[0;36m$1\e[0m' from \e[0;34;42m$omp_path/themes\e[0m to \e[0;34;42m\$HOME/current-omp/\e[0m"
echo -e "$uhost:\e[0;36m~\e[0m$ cp $omp_path/themes/$1 \$HOME/current-omp/"
#test -d $HOME/current-omp/ && test ! -r $HOME/current-omp/$1 && cp $omp_path/themes/$1 $HOME/current-omp/ || echo "File possibly already exists or No such directory"
#test ! -d $HOME/current-omp/ && mkdir $HOME/current-omp && cp $omp_path/themes/$1 $HOME/current-omp/
test ! -d $HOME/current-omp/ && mkdir $HOME/current-omp/
test ! -r $HOME/current-omp/$1 && cp $omp_path/themes/$1 $HOME/current-omp/
test -r $HOME/current-omp/$1 && echo -e "\e[0;33mCopied \e[0m'\e[0;36m$1\e[0m' to \e[0;34;42m\$HOME/current-omp/\e[0m"

# Adjust/add oh-my-posh init config line to reflect location of configuration 
add_theme="echo \"eval \\\"\$(oh-my-posh init bash --config ~/current-omp/$1)\\\"\" >> ~/.profile" 
#echo "eval \"\$(oh-my-posh init bash --config ~/current-omp/$1)\"" >> ~/.profile
echo -e "\e[0;33mConfiguring \e[0;36m.profile\e[0m or \e[0;36m.bash_profile \e[0mto use theme: '\e[0;36m$1\e[0m'\e[0m"
echo -e "$uhost:\e[0;36m~\e[0m$ $add_theme\e[0m"
test -r $HOME/current-omp/$1 && echo "eval \"\$(oh-my-posh init bash --config ~/current-omp/$1)\"" >> ~/.profile
echo "DONE"
exit 0
