#!/bin/sh

# uninstall old versions
echo "Uninstalling old versions..."
for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done

# update apt and install packages to allow apt to use repository over https
echo "Updating apt and installing https dependencies..."
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg

# add docker's official gpg key
echo "Adding docker's official gpg key..."
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

# setup the repository
echo "Setting up the repository..."
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# update apt package index
echo "Updating apt package index..."
sudo apt-get update

# install docker engine
echo "Installing docker engine..."
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# configure non-root user access
echo -e "Next steps:\n\tConfiguring non-root user access..."
# USER=$(whoami)
# sudo groupadd docker
# sudo usermod -aG docker $USER
# newgrp docker

# verify docker installation is successful
# sudo service docker start
# sudo docker run hello-world

