#!/bin/bash
echo "Installed python versions"
ls /usr/bin/python*\.?

echo
echo "Current python(3) version" 
# echo "python: "
# echo "python:" $(eval $(echo $(python --version)))
echo "python:" $eval $eval $cat <(python --version)
# echo python: echo $'python')
echo "python3:" $(echo $(python3 --version))
